#!/usr/bin/env python
# -*-coding:utf8-*-
import requests
import sys
from bs4 import BeautifulSoup
reload(sys)
sys.setdefaultencoding("utf-8")


# 获取电影名
def get_movie(soup,name):
    titles=soup.find_all(class_="title")
    for title in titles:
        if title.string[1]!='/':                   # 去除其他同名
            name.append(title.string)
    return name


# 获取电影排名和评分
def get_number_score(soup,number,score):
    number_score=soup.find_all('em')
    for i in range(len(number_score)):
        if i%2==0:
            number.append(number_score[i].string)
        else:
            score.append(number_score[i].string)
    return number,score

name=[];number=[];score=[]                         # 变量初始化
f=open('movie.txt','w')
# 得到豆瓣top250的电影
for i in range(10):
    url='http://movie.douban.com/top250?start=%s&filter=&type=' %(i*25)
    html=requests.get(url).text
    soup=BeautifulSoup(html,"lxml")
    name=get_movie(soup,name)
    (number,score)=get_number_score(soup, number, score)
# 将结果写入文件
for j in range(len(name)):
    title_str='%s %s %s' %(number[j],name[j],score[j])
    f.writelines(title_str+'\n')

f.close()



